// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQELVADL3p9hKi_sUE7tEXWsno5T35eY',
    appId: '1:680606890255:web:2ec0b378e4926c0376667a',
    messagingSenderId: '680606890255',
    projectId: 'flash-chat-3ccc3',
    authDomain: 'flash-chat-3ccc3.firebaseapp.com',
    storageBucket: 'flash-chat-3ccc3.firebasestorage.app',
    measurementId: 'G-GDV57WXZ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzx1rsqjw4BjAPFNGJaO1KT8hx0SzOdU',
    appId: '1:680606890255:android:15f375fb16675d8276667a',
    messagingSenderId: '680606890255',
    projectId: 'flash-chat-3ccc3',
    storageBucket: 'flash-chat-3ccc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-nayg0icFAlfeQirxHcI9jX4LfxBLDI',
    appId: '1:680606890255:ios:d722cccd072080b976667a',
    messagingSenderId: '680606890255',
    projectId: 'flash-chat-3ccc3',
    storageBucket: 'flash-chat-3ccc3.firebasestorage.app',
    iosBundleId: 'com.alexteringer9.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-nayg0icFAlfeQirxHcI9jX4LfxBLDI',
    appId: '1:680606890255:ios:4664fbc0bfecdf4576667a',
    messagingSenderId: '680606890255',
    projectId: 'flash-chat-3ccc3',
    storageBucket: 'flash-chat-3ccc3.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQELVADL3p9hKi_sUE7tEXWsno5T35eY',
    appId: '1:680606890255:web:95a01dd29337fa9576667a',
    messagingSenderId: '680606890255',
    projectId: 'flash-chat-3ccc3',
    authDomain: 'flash-chat-3ccc3.firebaseapp.com',
    storageBucket: 'flash-chat-3ccc3.firebasestorage.app',
    measurementId: 'G-HT9LM0SXFN',
  );
}
